#!/bin/bash

# All of these scripts are from:
# http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/

echo "weasel words: "
weasel $1
echo
echo "passive voice: "
passive $1
echo
echo "duplicates: "
dups $1
echo
echo "possibly incorrect: "
typos $1
